site_name: Pent-Hive Docs
nav:
  - Home: index.md
  - About: about.md
  - Docs:
    - Overview: documentation/overview.md
    - How It Works: documentation/how_it_works.md
    - CLI Docs: documentation/cli_docs.md
    - YAML API Docs:
      - Bee Specification: documentation/api/bee_spec.md
      - Hive Specification: documentation/api/hive_spec.md
      - Queen Specification: documentation/api/queen_spec.md
  - Examples:
    - Basic Usage: examples/basic_usage.md

theme:
  name: material

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - callouts
